### ISSUE TITLE
提供类似 antd CascadeSelect 的搜索功能

### ISSUE THREAD

**Issue by lpgray** [uxcore/uxcore-cascade-select#26]
![image](https://user-images.githubusercontent.com/1625503/44516607-1fc67480-a6f8-11e8-8380-66e795360f07.png)

**Comment by fuxun2008** [comment]
需求：1. 支持模糊搜索；2. 支持省、市、区关键字查询；3. 开启搜索节流；4. 是否需要支持远程数据源搜索？这个看场景~

**Comment by eternalsky** [comment]
前端不建议实现这么复杂的搜索，建议参考 select 里的 onSearch 和 filterOption，模糊搜索应该让服务端去解决。

**Comment by eternalsky** [comment]
@fuxun2008 建议让宜搭服务端提供一个数据的接口，而不用埋在组件里的那份，模糊搜索让服务端去做，前端去做性能太差。

**Comment by lpgray** [comment]
这个特性已经在 0.7.9 版本实现

**Comment by lpgray** [comment]
![image](https://user-images.githubusercontent.com/1625503/45264087-655d9e00-b469-11e8-9df0-25cde66c27a8.png)
